### ISSUE TITLE
Missing Info!

### ISSUE THREAD

**Issue by rangersmyth74** [b8ff/RansomWare#1]
Hey b8ff. I just watched a youtube video of the RansomWare that you made. I want to say that you python code is wonderful and you did outstanding work! I am learning cryptography and made my own ransom python files. What I would love to know and if you could point me in the right direction is to how you connected the ransomware to the discord server and how you set that up. I am on your youtube channel. 

What would be wonderful if its not a secret, if you could help me out as I would love to be able to do the same. 

If not, thanks for the files, I am learning so much from it already.

Ranger.

**Comment by TheBlackCookie** [comment]
if your looking to send messages to the discord server, you can use webhooks its very easy to use.

**Comment by b8ff** [comment]
Yeah as TheBlackCookie said you can easily use webhooks to send messages to discord. Check "utils.py" to see how i did it.

**Comment by TheBlackCookie** [comment]
> Yeah as TheBlackCookie said you can easily use webhooks to send messages to discord. Check "utils.py" to see how i did it.

I think its in main.py Line 128

**Comment by TheBlackCookie** [comment]
the function is in utils.py

**Comment by rangersmyth74** [comment]
Thanks, guys for the info!!  

Blessings on your journey in life.

Ranger,

**Comment by TheBlackCookie** [comment]
add my discord il guild you ex#1414
